services:
  katarive:
    build: .
    user: "${UID}:${GID}"
    ports:
      - 9421:9421
    depends_on:
      - voicevox
    volumes:
      - ./data:/app/data
      - ./.cache:/app/.cache
    environment:
      - KATARIVE_VOICEVOX_SERVER=http://voicevox:50021
    restart: on-failure
    networks:
      - katarive

  voicevox:
    image: voicevox/voicevox_engine:nvidia-latest
    container_name: voicevox-nvidia
    ports:
      - "50021:50021"
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      katarive:
        aliases:
          - voicevox

networks:
  katarive:
    driver: bridge
